betagouv/collectif-objets

- README.md
- www/app/assets/stylesheets/application.css
- www/app/controllers/recensements_controller.rb
- www/app/javascript/controllers/recensement_controller.js
- www/app/javascript/controllers/recensement_form/upload_photo_controller.js
- www/app/javascript/controllers/recensement_form/uploader_controller.js
- www/app/views/recensements/_form.html.erb
- www/app/views/recensements/_form_upload_photo.html.erb
- www/lib/tasks/users.rake
> WIP photos UX

- app/components/communes/recensement_form_radio_component.html.erb
- app/helpers/recensement_helper.rb
- app/lib/co/pdf/formulaire/questions_concern.rb
- app/lib/co/pdf/rapport/recensement_prawn.rb
- app/presenters/recensement_presenter.rb
- app/views/conservateurs/objets/_recensement_attribute.html.erb
- app/views/recensements/_form.html.erb
- config/locales/fr.yml
- spec/features/communes/recensement_spec.rb
- spec/features/communes/recomplete_dossier_spec.rb
- spec/features/conservateurs/accept_dossier_spec.rb
- spec/features/conservateurs/reject_dossier_spec.rb
fix #107
au passage corrige un pb d'affichage de la valeur overridée par l'analyse coté commune
> distinction etat objet edifice + remonter photos

- app/admin/conservateurs.rb
- app/assets/stylesheets/recensements.css
- app/views/conservateurs/objets/show.html.erb
> afficher les photos de recensement en galerie côté conservateurs 

- app/controllers/recensements_controller.rb
- app/models/recensement.rb
- app/services/communes/create_recensement_service.rb
- config/locales/fr.yml
- spec/features/communes/read_rapport_spec.rb
- spec/features/communes/recensement_spec.rb
- spec/features/communes/recomplete_dossier_spec.rb
- spec/features/conservateurs/accept_dossier_spec.rb
- spec/features/conservateurs/reject_dossier_spec.rb
- spec/services/communes/create_recensement_service_spec.rb
- better error handling when commune is invalid
- remove recensement after_create to set dossier
> Refactor recensement creation

- app/components/photo_upload_component.html.erb
- app/views/pages/aide.html.erb
dans le formulaire :
dans la FAQ :
> ajouter explications licences photos

- app/components/photos_upload_group_component.html.erb
- app/components/photos_upload_group_component.rb
- app/controllers/conservateurs/analyses_controller.rb
- app/controllers/recensements_controller.rb
- app/frontend/stimulus_controllers/recensement_controller.js
- app/frontend/stimulus_controllers/recensement_form/existing_photo_controller.js
- app/lib/co/recensements/analyse_params_parser.rb
- app/lib/co/recensements/params_parser.rb
- app/models/recensement.rb
- app/views/recensements/_form.html.erb
- db/migrate/20221103170555_add_confirmation_sur_place_and_skip_photos_to_recensement.rb
- db/schema.rb
- spec/factories/recensement.rb
- spec/lib/co/recensements/params_parser_spec.rb
- spec/services/communes/create_recensement_service_spec.rb
>  refactor recensements checkboxes pour les stocker en DB

- app/lib/co/recensements/params_parser.rb
- app/models/recensement.rb
- config/locales/fr.yml
- db/migrate/20221121104233_fix_recensements_confirmation_pas_de_photos.rb
- db/schema.rb
- spec/factories/recensement.rb
- spec/lib/co/recensements/params_parser_spec.rb
> empecher confirmation_pas_de_photos quand il y a des photos

- app/components/conservateurs/objet_card_component.rb
- app/helpers/application_helper.rb
- app/models/analyse.rb
- app/policies/conservateurs/analyse_policy.rb
- app/views/conservateurs/communes/show.html.erb
- app/views/conservateurs/communes/show_analyse_saved.html.erb
- spec/policies/conservateurs/analyse_policy_spec.rb
> fix dossier rejete ne devrait pas pouvoir etre analysé

- app/components/communes/objet_card_component.rb
- app/components/conservateurs/objet_card_component.rb
- app/components/objet_card_component.rb
- app/controllers/communes/objets_controller.rb
- app/controllers/conservateurs/communes_controller.rb
- app/lib/co/communes/objets_list.rb
- app/models/recensement.rb
- app/views/communes/objets/_cards.html.erb
- app/views/communes/objets/_list.html.erb
- app/views/communes/objets/index.html.erb
- app/views/communes/objets/recensement_saved.html.erb
- app/views/conservateurs/communes/show.html.erb
- app/views/conservateurs/communes/show_analyse_saved.html.erb
- app/views/edifices/_list.html.erb
- app/views/edifices/_title.html.erb
- app/views/objets/_cards.html.erb
- app/views/objets/_cards_grid_layout.html.erb
- app/views/objets/index.html.erb
- app/views/objets/show.html.erb
- spec/components/previews/communes/objet_card_component_preview.rb
- spec/components/previews/conservateurs/objet_card_component_preview.rb
- spec/components/previews/objet_card_component_preview.rb
- spec/features/conservateurs/accept_dossier_spec.rb
- spec/features/conservateurs/reject_dossier_spec.rb
- spec/jobs/synchronizer/objet_builder_spec.rb
> introduction des édifices

- contenus/fiches/restauration.md
> Changement titre fiche

- app/mailers/admin_mailer.rb
- app/views/admin_mailer/campaign_planned.text.erb
- app/views/admin_mailer/sanity_check_alert.text.erb
> ajouter nom environnement dans les mail admins

- Gemfile
- Gemfile.lock
- app/controllers/conservateurs/accepts_controller.rb
- app/controllers/objets_controller.rb
- app/lib/co/communes/objets_list.rb
- app/lib/co/departement_stats.rb
- app/models/objet.rb
- app/services/campaigns/compute_campaign_stats_service.rb
> suppression gem activerecord_where_assoc

- app/mailers/user_mailer.rb
- app/models/dossier_completion.rb
- lib/mailer_previews/user_mailer_preview.rb
- spec/mailers/user_mailer_spec.rb
Proposition pour l'issue https://github.com/betagouv/collectif-objets/issues/425
Les tests user_mailer_spec.rb passent en local
> Refactoring du UserMailer en utilisant le GlobalID

- app/jobs/sanity_checks_job.rb
- app/mailers/admin_mailer.rb
- app/mailers/campaign_v1_mailer.rb
- app/mailers/conservateur_mailer.rb
- app/mailers/custom_devise_mailer.rb
- app/mailers/user_mailer.rb
- app/models/magic_link.rb
- config/environments/test.rb
- config/locales/fr.yml
- spec/features/communes/sign_in_with_token_spec.rb
- spec/mailers/user_mailer_spec.rb
- spec/models/magic_link_spec.rb
> refactor: harmonisation du passage des params aux mailer

- app/frontend/stimulus_controllers/print_controller.js
- app/views/shared/_dossier_rapport.html.haml
> simplification du JS pour imprimer les rapports

- .rubocop.yml
- app/components/objet_page_component/objet_page_component.haml
- app/jobs/generate_bordereau_pdf_job.rb
- app/jobs/synchronizer/api_client_sql.rb
- app/jobs/synchronizer/objet_builder.rb
- app/jobs/synchronizer/synchronize_objets_job.rb
- app/models/bordereau/pdf.rb
- app/models/objet.rb
- app/views/conservateurs/bordereaux/_edifice.html.haml
- app/views/conservateurs/bordereaux/new.html.haml
- db/migrate/20230511070126_add_palissy_dpro_and_prot_to_objets.rb
- db/schema.rb
- spec/factories/objet.rb
- spec/jobs/synchronizer/objet_builder_spec.rb
discuter avec Romuald : 
| DPRO | nombre d’objets | exemples |
|-|-|-|
| inscrit au titre objet | 142823 objets | PM52001911 PM52001912 PM52001680 |
| classé au titre objet | 88588 objets | PM52000003 PM52000004 PM52000001 |
| classé au titre immeuble | 2965 objets | PM52000046 PM52000171 PM52000303 |
| classé comme un ensemble historique mobilier | 305 objets | PM88002036 PM88002037 PM88002038 |
| désinscrit | 295 objets | PM51003182 PM58000983 PM12001479 |
| inscrit au titre immeuble | 168 objets | PM52001900 PM52001903 PM52001902 |
| inscrit MH | 66 objets | PM26000482 PM30000794 PM58000633 |
| inscrit au titre des Monuments historiques | 62 objets | PM60005287 PM60005288 PM60005289 |
| classé au titre objet partiellement | 33 objets | PM18000215 PM18000430 PM21002427 |
| sans …
> importer DPRO et PROT de palissy + dans les bordereaux exporter uniquement les classés

- app/controllers/concerns/campaigns_controller_concern.rb
https://yeswehack.com/reports/others/136416
> réparation faille sécurité injection HTML dans la configuration des campagnes

- app/controllers/admin/campaigns_controller.rb
- app/controllers/concerns/campaign_recipients_controller_concern.rb
- app/controllers/concerns/campaigns_controller_concern.rb
- app/controllers/conservateurs/campaigns_controller.rb
- app/models/concerns/campaigns/force_step_up_concern.rb
- app/policies/conservateurs/campaign_recipient_policy.rb
- app/views/admin/campaigns/show.html.haml
- app/views/shared/campaign_recipients/_mail_preview.html.haml
- app/views/shared/campaign_recipients/_show_content.html.haml
- config/routes.rb
- spec/policies/conservateurs/campaign_recipient_policy_spec.rb
> réparation admin forcer fin campagne + nouvelle action admin changer tous les emails

- app/jobs/sanity_checks_job.rb
- app/views/pages/home.html.haml
> remplacer Adrien par Brice

- app/views/conservateurs/departements/_stats.html.haml
ce sont les stats du departement et pas de la campagne
> correction wording sur la page conservateurs/departement 

- Gemfile
- Gemfile.lock
webdrivers is not needed anymore cf https://github.com/titusfortner/webdrivers
> update selenium-webdrivers to 4.16 and remove deprecated webdrivers gem

- app/models/campaign.rb
> correction de l’affichage du message d’overlap de campagnes

- package-lock.json
- package.json
j’ai testé un chemin complet de recensement et d’examen en desktop et mobile et je n’ai pas vu de différences
> update DSFR from 1.10.2 to 1.11

- config/application.rb
- config/environments/development.rb
J’ai créé une nouvelle app rails 7.1.2 en local pour voir les différences de fichiers de config et modifier nos fichiers respectivement
j’ai aussi suivi ce doc https://edgeguides.rubyonrails.org/7_1_release_notes.html
il y a peu de changements et à priori je n’ai pas vu d’impact
> update rails config with 7.1 defaults

- app/views/pages/accueil_conservateurs.html.haml
> Ajout de l'infolettre #4 sur la page d'accueil conservateurs

- config/environments/production.rb
seen in https://allaboutcoding.ghinda.com/first-commits-in-a-ruby-on-rails-app
> prod console in sandbox mode by default

- app/controllers/admin/comments_controller.rb
- app/models/admin_comment.rb
- app/models/admin_user.rb
- app/models/commune.rb
- app/views/admin/communes/show.html.haml
- config/routes.rb
- db/migrate/20240119170321_rename_active_admin_comments_table.rb
- db/schema.rb
> refactor: renamed ActiveAdminComment to AdminComment + migration

- app/frontend/stylesheets/components/small_components.css
- app/views/pages/accueil_conservateurs.html.haml
- app/views/pages/home.html.haml
- app/views/presse/index.html.haml
- app/views/presse/show.html.haml
- app/views/shared/_video_embed.html.haml
- app/views/shared/_video_reportage_canal32.haml
- contenus/content_blobs/documentation_commune.md
- contenus/content_blobs/documentation_conservateur.md
- spec/features/accessibility_spec.rb
suite à cette PR on pourra vider le bucket s3 public excepté le fichier de seeds
> migration des vidéos depuis notre S3 public vers tube.numerique.gouv.fr

- db/migrate/20240123094037_disable_postgis.rb
- db/schema.rb
this is step 2 out of 3 : disable the postgis extension in the database
> disable postgis in db

- app/controllers/content_blobs_controller.rb
- app/controllers/fiches_controller.rb
will fix and avoid next
https://sentry.incubateur.net/share/issue/2f7a53afe30a418b92b734f4286aade9/
https://sentry.incubateur.net/share/issue/7cb967364b2c467abf47fc6b47c811c7/
> 404 plutot que 500 sur les fiches et contenus inconnus

- lib/mailer_previews/user_mailer_preview.rb
correction https://sentry.incubateur.net/organizations/betagouv/issues/82704
> fix mail preview UserMailer.validate_email

- config/initializers/good_job.rb
cf https://www.notion.so/atelier-numerique/automatiser-rendre-r-gulier-l-import-c36dcd917ae64e8eb467720752572973
les jobs doivent être exécutés dans un certain ordre
1. Objets
2. Communes
3. Edifices
et les Photos après les Objets
> CRON jobs de synchronisation de tous les modèles

- app/components/message_component.rb
- app/components/message_component/message_component.haml
- app/frontend/entrypoints/all.css
- app/frontend/stylesheets/bootstrap_subset.css
- app/frontend/stylesheets/dsfr_overrides.css
- app/frontend/stylesheets/utilities.css
- app/views/communes/messages/index.html.haml
- app/views/conservateurs/messages/index.html.haml
- app/views/pages/conditions.html.haml
- app/views/pages/confidentialite.html.haml
- app/views/shared/header/_header_conservateur_search.haml
- app/views/shared/messages/_email_address_hint.html.haml
- app/views/shared/messages/_form.html.haml
- app/views/shared/messages/_list.html.haml
- config/locales/fr.yml
- contenus/content_blobs/documentation_commune.md
- contenus/content_blobs/documentation_conservateur.md
- package-lock.json
- package.json
- spec/features/conservateurs/messages_spec.rb
> Ajout de la mention RGPD dans la messagerie

- app/controllers/mail_previews_controller.rb
- app/mailer_views/campaign_v1_mailer/_objet_photo.mjml
- app/views/admin/campaigns/edit.html.haml
- app/views/admin/campaigns/edit_recipients.html.haml
- app/views/admin/campaigns/index.html.haml
- app/views/admin/campaigns/mail_previews.html.haml
- app/views/admin/campaigns/new.html.haml
- app/views/admin/communes/index.html.haml
- app/views/admin/communes/show.html.haml
- app/views/admin/conservateurs/_form.html.haml
- app/views/admin/conservateurs/edit.html.haml
- app/views/admin/conservateurs/index.html.haml
- app/views/admin/conservateurs/new.html.haml
- app/views/admin/exports/memoire/index.html.haml
- app/views/admin/exports/memoire/new.html.haml
- app/views/admin/exports/memoire/show.html.haml
- app/views/admin/exports/mpp/_table.haml
- app/views/admin/session_codes/index.html.haml
- app/views/pages/plan.html.haml
- app/views/shared/campaigns/_form.html.haml
- app/views/shared/campaigns/_stats.html.haml
- public/404.html
- public/500.html
- spec/factories/admin_user.rb
- spec/factories/dossier.rb
- spec/features/admin_pages_spec.rb
- spec/features/error_spec.rb
> Corrige l'accessibilité de l'administration

- app/controllers/admin/campaigns_controller.rb
- app/controllers/admin/conservateurs_controller.rb
> Corrige des N+1 dans les contrôleurs

- app/views/shared/campaigns/_show_content.html.haml
- config/locales/fr.yml
Précise aux CAOA que les données seront perdues s'ils lancent une nouvelle campagne sur une commune en cours  d'examen.
Passe en majuscules certaines formules comme "Madame la Maire".
> Quelques changements de wording

- app/views/pages/accueil_conservateurs.html.haml
- app/views/pages/home.html.haml
- app/views/presse/index.html.haml
- app/views/presse/show.html.haml
- app/views/shared/_transcript.haml
- app/views/shared/_video_canal32.html.haml
- app/views/shared/_video_embed.html.haml
- contenus/content_blobs/aide_en_ligne.md
- contenus/content_blobs/documentation_conservateur.md
> Ajoute les transcription des vidéos

- app/components/galerie/miniatures_component/miniatures_component.html.haml
- app/views/conservateurs/analyses/edit.html.haml
> Corrige la mise en page de la page analyse

- app/components/galerie/miniatures_component/miniatures_component.html.haml
- app/helpers/application_helper.rb
- app/jobs/auto_submit_dossier_job.rb
- app/views/admin/conservateurs/index.html.haml
- app/views/shared/_header.haml
- config/locales/fr.yml
> Corrections et optimisations diverses

- app/frontend/stimulus_controllers_standalone/conservateur_map_controller.js
- app/frontend/stylesheets/components/map.css
- app/views/conservateurs/departements/_tab_carte.html.haml
- db/seeds.rb
> Afficher toutes les communes du département sur la carte

- README.md
- app/mailer_views/campaign_v1_mailer/_objet_photo.mjml
- app/mailer_views/shared/_footer.mjml
- app/mailer_views/shared/_header.mjml
- app/views/conservateurs/departements/index.html.haml
- app/views/conservateurs/passwords/new.haml
- app/views/conservateurs/sessions/new.html.haml
- app/views/devise/mailer/define_password_instructions.mjml
- app/views/devise/mailer/reset_password_instructions.mjml
- config/environments/production.rb
- config/initializers/contact_email.rb
- config/initializers/devise.rb
- public/404.html
- public/500.html
> feat: Récupère la configuration email depuis l'environnement
