betagouv/collectif-objets

app/components/gallery_component.rb
cf https://sentry.incubateur.net/organizations/betagouv/issues/4728/
you cannot call .url when it's not been processed yet. you have to call image_tag with the attachment itself so that it delays the actual processing of the variant
=> fix gallery problem

app/components/conservateurs/analyse_override_component.rb, app/components/conservateurs/communes_search_component.html.erb, app/components/conservateurs/objet_card_component.html.erb, app/components/conservateurs/objet_card_component.rb, app/controllers/conservateurs/communes_controller.rb, app/lib/co/conservateurs/communes_search.rb, app/models/concerns/communes/include_counts_concern.rb, app/models/concerns/recensements/booleans_concern.rb, app/models/conservateur.rb, app/models/dossier.rb, app/models/objet.rb, app/models/recensement.rb, app/views/conservateurs/departements/show.html.erb, app/views/conservateurs/objets/_recensement_attributes.html.erb, app/views/conservateurs/objets/show.html.erb, config/locales/fr.yml, spec/features/conservateurs/reset_password_spec.rb
changements côté conservateurs :
- la colonne objets "en peril" devient "objets prioritaires"
- dans la liste des objets sur une commune on n'affiche plus que le badge prioritaire (en plus en peril)
- reparation des tags au lieu des badges sur cette même liste de cartes
- quelques réparations d'ergonomies de cacher des infos selon l'état d'avancement du dossier
=> Recensements prioritaires côté conservateurs

app/views/shared/_flashes.html.haml
En me baladant sur les différents parcours utilisateur, j'ai remarqué que les messages d'alerte étaient collés au header, comme on peut le voir sur cette capture d'écran :
Voilà ce que ça donne avec une marge en plus : 
J'en ai profité pour faire un léger refactoring de flashes.html
=> Ajout d'une marge sur les message d'alerte

app/frontend/stylesheets/print.css, app/presenters/rapport_presenter.rb, app/views/shared/_dossier_rapport.html.haml, app/views/shared/rapport/_recensement.html.haml
le bug principal de pages tronquées provenait de la `height` settée en JS par le DSFR sur les tabs. je l’ai corrigée en forçant `height: auto` en version print.
Le reste des changements sont des petites améliorations du layout : 
- ne pas afficher "Vue groupée par fiches quand il n’y a aucune fiche"
- corrections de marges en vue print
- pas de retour a la page apres le dernier objet pour eviter une page blanche
=> corrections CSS print pour le rapport - bug tabs

app/controllers/presse_controller.rb
devrait corriger https://sentry.incubateur.net/organizations/betagouv/issues/31294 des attaqueurs essaient de XSS a partir de cette URL
=> erreur 404 pour les urls d’articles de presse inexistants

app/components/communes/objet_card_component.rb, app/controllers/admin/dossiers_controller.rb, app/helpers/objet_helper.rb, app/views/admin/communes/show.html.haml, app/views/communes/objets/show.html.haml
admin
- affichage de l’état du dossier pour les communes ayant recensé tout en haut de la page `admin/communes#show`
- suppression d’une colonne en trop dans le tableau de recensements
- amélioration des wordings de "retour en construction"
interface communes
- apres analyse, un badge vide s’affichait dans la liste des objets et en haut de la page objet
- apres analyse, il peut y avoir un badge "commentaires" si le conservateur a laissé un commentaire, mais ce commentaire n’apparaissait pas sur la page objet, ce qui était perturbant. je l’affiche maitnenant un peu n’importe comment mais au moins c’est plus cohérent
=> corrections mineures d’affichage des dossiers en fonction des états

app/controllers/conservateurs/departements_controller.rb, app/frontend/stimulus_controllers_standalone/conservateur_map_controller.js, app/helpers/commune_helper.rb, app/helpers/dossier_helper.rb, app/models/commune.rb, app/models/concerns/communes/include_counts_concern.rb, app/models/dossier.rb, app/models/recensement.rb, app/views/conservateurs/departements/_communes_search.html.haml, app/views/conservateurs/departements/_map.html.haml, app/views/conservateurs/departements/_map_sidebar_commune_template.html.haml, config/locales/fr.yml, contenus/content_blobs/documentation_conservateur.md, spec/factories/objets.rb, spec/factories/recensement.rb, spec/models/commune_spec.rb
L'objectif est de faire évoluer la page de visualisation d'un département côté conservateur (/conservateurs/departements/ID_DU_DEPARTEMENT), et plus précisément le tableau des communes, qui ressemble actuellement à ça :
Voici la maquette vers laquelle je dois aller :
Dans la colonne Objets prioritaires, il y a désormais une distinction entre les objets "disparus" et les objets "en péril" (en très mauvais état). Un objet est dit "prioritaire" s'il est disparu ou en péril.
Le tri de la colonne Objets prioritaires se fait en fonction du nombre total d'objets prioritaires.
Le filtre d'objets prioritaires (via la select box en haut du tableau) permet de ne remonter que les communes ayant au moins un objet prioritaire du critère choisi (disparu ou en péril).
=> Évolution de la vue d'un département côté conservateur

app/views/communes/recensements/_step1.html.haml
cf https://atelier-numerique.notion.site/3c1b452d1f5048719a4b879ec9208845?v=95aca3f8728a4ddd8ee25be0c6b07def&p=d90d37aed14a4e108d69664021e76406&pm=s
=> correction du lien vers la messagerie depuis la modale objet introuvable

app/views/edifices/_list.html.haml
je suis tombé sur cette ligne et j’ai mis un moment à la comprendre
`edifices.reduce { |a_moins_de_6_objets, edifice| a_moins_de_6_objets && edifice.objets.count <= 6 }` 
est-ce qu’il y avait une raison d’utiliser `reduce` qui m’échappe ? il me semble que c’est plus lisible avec `all?`. J’ai utilisé un numbered parameter `_1` pour la concision mais on peut aussi laisser `.all?{ |edifice| edifice.objets.count <= 6}`
=> simplification du filtre pour afficher la liste d’édifices

app/views/communes/recensements/_step3.html.haml, spec/features/communes/recensement_spec.rb
je ne sais pas vraiment ce qui se passait, ceci est un fix un peu rapide où j’ai juste fait en sorte que le markup html soit exactement identique sur la step 3 photos que sur les 1 et 2 ou les modales marchaient
j’ai modifié les tests pour qu’on soit prévenus si ça se reproduit
il faudra néanmoins un jour se pencher sur cette ouverture de modale via Turbo un peu sauvage, le controller stimulus auto open modal est vraiment un hack
=> réparation de la modale de recensement sans photos

app/jobs/sanity_checks_job.rb
en local le cron job censé modifier les statuts des campagnes ne tourne pas. On se retrouve avec des campagnes dans des états incohérents.
J’ai eu peur que ça se produise en prod, alors j’ai écrit ce sanity check qui nous avertira si ça se produit un jour (par exemple si le cron job ne tourne plus). J’ai vérifié et il n’y a aucune occurence en prod pour l’instant 😅
=> ajout d’un sanity check pour valider la cohérence des dates de campagnes et leurs statuts

app/frontend/stylesheets/utilities.css, app/views/conservateurs/departements/_campaigns.html.haml, app/views/conservateurs/departements/_stats.html.haml
cf https://www.notion.so/atelier-numerique/3c1b452d1f5048719a4b879ec9208845?v=95aca3f8728a4ddd8ee25be0c6b07def&p=4d68f37a6af24364b165895015a76f8a&pm=s
sur mobile rien ne change, c’est toujours un accordéon
j’ai dupliqué le code pour faire simple, c’est dans un unique fichier donc ca me parait ok
=> conservateurs: améliorations de l’UI de la vue d’un departement

Gemfile, Gemfile.lock
les bonnes pratiques semblent indiquer d’utiliser le pessimistic operator cf https://stackoverflow.com/questions/9265213/should-i-specify-exact-versions-in-my-gemfile
cf https://thoughtbot.com/blog/rubys-pessimistic-operator
> ~> 1.1 means that when you bundle install, you’ll get the highest-released gem version of thin between the range >= 1.1 and < 2.0.
**dans cette PR j’ai mis des contraintes pessimistes qui font que `bundle update` mettra à jour toutes les versions mineures et patch mais jamais majeures.**
je pense que pour la maintenance future c’est aussi plus sécurisant que `bundle update` ne déclenche pas de mises à jour majeures
=> harmonisation des contraintes pessimistes dans le gemfile

app/models/objet.rb, spec/factories/objets.rb, spec/models/commune_spec.rb, spec/models/objet_spec.rb, spec/policies/communes/recensement_policy_spec.rb
Pour les communes dont le recensement n'était pas terminé, les objets non recensés ne s'affichaient plus sur la page commune côté conservateur.
En bonus, les factories d'objets avec recensement ne fonctionnaient pas bien car elles créaient 2 objets Recensement.
=> Correctif d'un bug n'affichait plus certains objets sur la page d'une commune

app/views/conservateurs/analyses/_recensement_attributes.html.haml, spec/features/conservateurs/accept_dossier_spec.rb
Changements validés avec Enora qui vont dans la direction de ces maquettes de refonte de la page examen
Les liens dans les labels des checkboxes sont un peu genants.
D’un, on clique souvent sur le label pour cocher les checkbox, quand il y a un lien c’est perturbant il faut cliquer a coté 
De deux, ça cause des soucis avec les E2E features specs capybara qui failent de temps en temps dès que je modifie un peu la page examen meme sur des choses non liées. J’ai observé et ce qu’il semble se passer c’est qu’il clique sur le lien au lieu de cliquer sur le label. ex de fail bizarre visible ici https://github.com/betagouv/collectif-objets/actions/runs/7263321701/job/19788341340
on utilisait cette méthode pour checker la checkbox
`find("a", text: /entretien des édifices/).find(:xpath, …
=> page examen, extraction des liens vers les fiches hors des labels de checkboxes

app/views/shared/rapport/_recensement.html.haml, config/environments/test.rb, spec/factories/recensement.rb, spec/features/conservateurs/accept_dossier_spec.rb, spec/rails_helper.rb
dans cette PR je fais deux choses
1. correction de la configuration d’active storage dans les features specs
je fixe le port du serveur rails lancé pendant les specs à `31337`, je le signale à Capybara ET à Active Storage
Sans ça, Active Storage n’arrive pas à générer des URLs d’images correctes. 
On ne s’en rendait pas compte car ça ne raise pas, mais jusque là les photos uploadées avec active storage en disk mode pendant les specs faisaient des erreurs 404 à l’affichage.
2. modification de `features/conservateurs/accept_spec.rb`
Je rajoute trois photos uploadées avec Active Storage Disk mode sur un des recensements testés dans cette spec 
Cela prépare au test de la galerie.
=> fix active storage disk mode in feature specs

app/components/conservateurs/analyse_override_editable_component/analyse_override_editable_component.html.erb, app/components/galerie/frame_component.rb, app/components/galerie/lightbox_component.rb, app/components/galerie/lightbox_component/lightbox_component.css, app/components/galerie/lightbox_component/lightbox_component.html.haml, app/components/galerie/miniatures_component.rb, app/components/galerie/miniatures_component/miniatures_component.css, app/components/galerie/miniatures_component/miniatures_component.html.haml, app/views/conservateurs/analyses/_recensement_attributes.html.haml, app/views/conservateurs/analyses/edit.html.haml, config/locales/fr.yml
refactors quasiment sans changements pour préparer le terrain et rendre la PR d’ajout des actions plus lisible
le seul changement est qu’on ne fait plus apparaître un titre à côté du titre de la galerie dans certains cas, ce n’était pas très utile
Quelques renommages bénins de variables et classes, et déplacements de fonctions entre composants de vue de la galerie
Passage des appels et définitions avec beaucoup de kwargs d’une ligne à plusieurs pour rendre lisible l’ajout et la suppression
Dans le template `analyses/edit` je fais un changement un peu bizarre. Je sors le tag de formulaire et je l’affiche vide `<form id="recensement" action="..." ...></form>`. 
Puis pour chaque input et label je rajoute attribut form qui pointe sur l’id : `<input form="recensement" type="..." />`. 
Le but …
=> Refactors de la galerie avant ajout des actions

app/components/impersonate_callout_component/impersonate_callout_component.haml, app/views/shared/_banners.html.haml
textes plus petits partout
flex-wrap: wrap pour que les boutons reviennent à la ligne plutot que faire déborder le scroll horizontal
=> amélioration de la vue responsive des bannières d’environnement et d’incarnation

app/views/conservateurs/campaign_recipients/show.html.haml, app/views/shared/campaign_recipients/_show_content.html.haml, app/views/shared/campaigns/_show_content.html.haml
Il est impossible de planifier une campagne (càd la passer de brouillon vers planifiée) si une ou plusieurs communes sont actives.
Pour l’instant quasiment le seul garde fou est fait dans la state machine en guard clause, ça fait une belle erreur 500 si un conservateur essaie quand même cf https://sentry.incubateur.net/organizations/betagouv/issues/79027
Dans cette PR je fais en sorte d’afficher ça plus clairement
Sur la page campaigns#show :
- ajout de texte avec un icone warning explicatif dans le callout
- bouton planifier disabled
- clarification dans la liste des destinataires de quelle commune est active
Sur la page destinataire, ajout d’un callout d’erreur
=> clarifier la contrainte des communes inactives pour planifier les campagnes

app/frontend/entrypoints/raise_on_purpose.js, app/frontend/stimulus_controllers/raise_js_error_controller.js, app/views/health/js_error.html.haml
mini PR de refacto pour supprimer un entrypoint JS utilisé uniquement sur la page de test des erreurs JS
préliminaire au retrait de Vite en faveur des importmaps
=> refactor du raise on purpose JS pour utiliser un stimulus controller

config/application.rb, config/environments/development.rb
c’est problématique pour nous d’activer cette nouvelle config de rails 7.1 car on a ce genre de lignes au niveau de base controllers :
`after_action :verify_authorized, except: :index`
certains enfants de ces base controllers n’implémentent pas l’action index. c’est un peu relou à modifier et c’est (c’était ?) la manière de faire recommandée de pundit
=> désactivation de raise_on_missing_callback_actions sur tous les envs

README.md, app/jobs/synchronizer/synchronize_communes_job.rb
https://api-lannuaire.service-public.fr/explore/dataset/api-lannuaire-administration/information/
c’est assez chouette. Les petits points d’attention sur cette API :
1. pagination par 100 et limitation des résultats aux 10.000 premiers
2. le type d’objet est dans un champ string qui contient un array JSON 👎 je fais un `startswith(pivot, '[{"type_service_local": "mairie",')` bien sale mais ça a l’air de marcher au vu du nombre de résultats
3. aucune info sur le rate limit de l’API mais ça a l’air de passer avec 0.5s d’écart entre les requêtes pour un refresh france entière en local
le 1. n’est pas un problème car on parcourait déjà département par département, et il y a moins de 10.000 communes par département
je me suis rendu compte qu’on ne met jamais à jour les emails des users de …
=> synchronisation des communes depuis l’API officielle Service Public

db/migrate/20240106113952_fusionner_edifices_doublons.rb, db/schema.rb
en prod, il y a 246 édifices qui sont invalides car leur doublon [code_insee, slug] n’est pas unique
cette migration les parcourt et les fusionne
1. on parcourt les paires problématiques [code_insee, slug]
3. on vérifie qu’il n’y a que deux édifices pour chaque paire
4. parmi ces deux on choisit prioritairement de garder celui qui a des objets si l’autre n’en n’a pas, ou celui qui a une ref merimee si l’autre n’en n’a pas
on vérifie à la fin que ça suffit à corriger tous les problèmes, c’est le cas, youpi
output du run local sur un dump de prod
```
== 20240106113952 FusionnerEdificesDoublons: migrating ========================
246 edifices sont invalides et partagent le même code_insee et slug
Pour 29106-chapelle-notre-dame-quilinen il y a un édifice avec ref (49928) et un autre sans …
```
=> fusion d’édifices avec le meme code insee et le meme slug

db/migrate/20240108153647_fix_dossier_with_submitted_at_nil.rb, db/schema.rb
Dans [cette PR](https://github.com/betagouv/collectif-objets/pull/1058) on a besoin de comparer les dates d'envoi des dossiers pour savoir si on envoie l'email pour les communes n'ayant que des objets verts.
Or il arrive que certains dossiers soient dans le statut `submitted` mais que la date `submitted_at` soit `nil`.
Ça ne devrait pas arriver, alors on migre la base en mettant à jour la date `submitted_at` à la valeur de `completed_at` de la commune, qui doivent être les mêmes en théorie.
=> Correctif pour les dossiers sans submitted_at

Makefile, README.md
Suite à une ré installation de ma machine, j'ai clarifié le processus d'installation et fait en sorte d'utiliser au maximum Homebrew qui fonctionne aussi sur Linux.
J'ai envisagé la possibilité de passer sur adsf plutôt que rbenv pour Ruby et NVM pour Node.js. À priori ça ne pose pas de problème, mais il faudrait adapter le Makefile.
=> docs: précisions pour l'installation sous Mac et Linux

config/initializers/active_storage.rb, spec/active_storage_safe_purge_spec.rb
Corrections : 
- Le monkey patch des blobs n’était pas chargé au bon endroit, il faut se brancher au hook spécifiques aux blobs : `ActiveSupport.on_load(:active_storage_blob)` et pas celui des attachments
Modifications : 
- Le monkey patch de vérification de la dangerosité n’est plus fait qu’à un seul endroit, le plus bas possible : `ActiveStorage::Blob.delete`
- On ne raise plus mais on skippe silencieusement le delete
- ajout de specs
- passage d’une liste d’exclusion des buckets dangereux à une liste d’inclusion des buckets sans danger, ça me paraît plus prudent (la liste d’exclusion ne contenait notamment pas le bucket de staging)
Tests manuels en local : 
- j’import un dump full de staging 
- je me connecte en tant que conservateur 
- je vais sur un dossier à examiner, sur un …
=> fix safeguard to prevent file deletions from prod & staging S3 buckets from local

app/jobs/campaigns/cron_job.rb, spec/jobs/campaigns/cron_job_spec.rb
Le job `Campaigns::CronJob` envoyait les emails de manière synchrone, ce qui pouvait le rendre long et risquait de le faire timeout côté Scalingo.
Ils sont désormais envoyés de manière asynchrone.
=> Envoi des emails objets verts en asynchrone

app/controllers/admin/users_controller.rb, app/controllers/users/magic_links_controller.rb, app/jobs/synchronizer/communes/revision.rb, app/models/user.rb, db/migrate/20240119181855_remove_users_role.rb, db/schema.rb, spec/factories/users.rb, spec/features/communes/read_rapport_spec.rb, spec/features/communes/recensement_spec.rb, spec/features/communes/send_message_spec.rb, spec/features/communes/sign_in_with_token_spec.rb, spec/features/conservateurs/accept_dossier_spec.rb, spec/models/bordereau/pdf_spec.rb
closes #929
aucun changements fonctionnels
la méthode `prevent_admin` ne faisait en fait rien, c’est un héritage de quand on avait une seule table `users` avec les admins et les users
=> remove users.role (with migration)

app/views/communes/recensements/_step1.html.haml, app/views/communes/recensements/_step2.html.haml, app/views/communes/recensements/_step3.html.haml, app/views/communes/recensements/fields/_photos.html.haml, app/views/pages/accueil_conservateurs.html.haml, app/views/pages/home.html.haml, app/views/recensements/_etapes_contenu.html.haml, config/locales/fr.yml, spec/mailers/campaign_v1_mailer_spec.rb
On utilise actuellement le terme conservateur pour désigner à la fois les CAOA et CMH.
L'idée est de remplacer "conservateur" par "conservateur d'antiquités et d'objets d'art" partout où l'on s'adresse aux communes. Principalement dans les emails de campagnes, la FAQ et sur quelques pages comme le formulaire de recensement par étapes.
Sybille mettra à jour de son côté la documentation et les fiches.
=> Remplacement du terme conservateur par CAOA

README.md, app/components/conservateurs/objet_card_component.rb, app/jobs/synchronizer/objets/revision_concern.rb, app/jobs/synchronizer/objets/revision_insert.rb, app/jobs/synchronizer/objets/revision_update.rb, app/jobs/synchronizer/objets/synchronize_all_job.rb, app/models/dossier.rb, app/views/conservateurs/communes/show.html.haml, spec/jobs/synchronizer/objets/revision_insert_spec.rb, spec/jobs/synchronizer/objets/revision_update_spec.rb
https://www.notion.so/atelier-numerique/import-Importer-les-objets-sur-les-communes-actives-758a50dcbea8405e820d64417c723291
- on créé et déplace maintenant des objets dans des communes actives
- on ne déplace cependant toujours pas depuis une commune active ayant déjà recensé l’objet
- suppression du mode interactif
côté commune : 
- badge pas encore recensé dans la liste
- l’objet peut être recensé
côté conservateur : 
- badge pas encore recensé dans la liste
- impossible à examiner, mais pas (plus) de bug
- si le conservateur examine et accepte le dossier, ça fonctionne, et l’objet apparait toujours en "pas encore recensé" mais il n’apparait pas dans le rapport. ça marche aussi côté commune post-examen
Il y a deux sous-cas si la commune commence à recenser le nouvel objet avant …
=> Import des objets sur les communes actives

app/jobs/sanity_checks_job.rb, app/mailers/admin_mailer.rb, app/views/admin_mailer/sanity_check_alert.text.erb
j’ai écrit ce petit sanity check supplémentaire pour verifier que les jobs de generation de bordereaux de recolement se depilent correctement
j’ai eu un doute car en local ce n’était pas le cas, mais j’ai lancé en prod et tout va bien.
=> ajout d’un sanity check sur les generations de bordereaux de recolement

app/controllers/objets_controller.rb, app/jobs/synchronizer/objets/batch/base.rb, app/jobs/synchronizer/objets/batch/eager_load_store.rb, app/jobs/synchronizer/objets/parser.rb, app/jobs/synchronizer/objets/revision.rb, app/jobs/synchronizer/objets/revision_insert_concern.rb, app/jobs/synchronizer/objets/revision_update_concern.rb
- ajout de logs dans la synchro objets + amélioration des logs existants
- refactos préliminaires pour rendre la PR #1159 plus lisible
- correction cas particulier Synchronizer::Objets::Batch::EagerLoadStore#add_edifice : les édifices ayant une REF doivent aussi apparaitre dans le hash indexé par slug et code insee
=> synchro objets : minor improvements and refactors

.rubocop.yml, app/jobs/synchronizer/objets/batch/base.rb, app/jobs/synchronizer/objets/batch/eager_load_store.rb, app/jobs/synchronizer/objets/batch/eager_loaded_records.rb, app/jobs/synchronizer/objets/parser.rb, app/jobs/synchronizer/objets/revision_edifice_concern.rb, app/jobs/synchronizer/objets/revision_update_concern.rb, app/models/commune.rb, app/models/concerns/communes/include_counts_concern.rb, app/models/concerns/dossiers/include_counts_concern.rb, app/models/departement.rb, app/models/objet.rb, app/models/pop_export.rb, app/views/shared/_objet_attributes.html.haml, db/migrate/20240208151633_add_palissy_depl_web_mosa_to_objets.rb, db/schema.rb, spec/jobs/synchronizer/objets/parser_spec.rb, spec/jobs/synchronizer/objets/revision_spec.rb
cf https://www.notion.so/atelier-numerique/G-rer-les-d-placements-d-objets-lors-de-l-import-79469ac8661b4286b24b60516d692b05
Je me suis permis de déployer une PR de petits refactos et un correctif : eef08e4bee9669ce0c8a7352f6a0cb2a04cbcc60 . Ça permet de rendre cette PR plus concise et lisible. 
J’ai aussi extrait dans une PR successive la MàJ du diagramme de schéma de base de données parce que ce changement faisait exploser le nombre de lignes modifiées dans cette PR 😬  #1162 
On importe trois nouveaux champs de Palissy :
- `palissy_DEPL` (`lieu_de_deplacement_de_l_objet`)
- `palissy_WEB` (`code_insee_commune_actuelle`)
- `palissy_MOSA` (`edifice_actuel`)
Et on ajoute trois champs supplémentaires dans la table objets: 
- `lieu_actuel_code_insee`
- `lieu_actuel_edifice_nom`
- …
=> 1. Import des objets déplacés (DEPL, WEB & MOSA)

app/jobs/synchronizer/log_concern.rb, app/jobs/synchronizer/logger.rb, app/jobs/synchronizer/objets/batch/base.rb, app/jobs/synchronizer/objets/batch/eager_load_store.rb, app/jobs/synchronizer/objets/revision.rb, app/jobs/synchronizer/objets/revision_insert_concern.rb, app/jobs/synchronizer/objets/revision_update_concern.rb, app/jobs/synchronizer/objets/synchronize_all_job.rb, spec/jobs/synchronizer/objets/revision_spec.rb
🔒  BASED ON #1159 🔒 
extraction d’une classe `Synchronizer::Logger` qui va être réutilisée côté synchro des communes. Ce Logger est maintenant responsable d’écrire dans un fichier ET de maintenir les compteurs. 
petit refacto de `Synchronizer::Objets::Revision` pour ajouter : 
- `#action` (qui vaut `:create, :update, :update_with_commune_change, :update_ignoring_commune_change` ou `:not_changed`) 
- et `#log_message`
un mini refacto qui en découle c’est que `revision#synchronize` renvoie maintenant `true` quand il n’y a aucun changement appliqué.
`Synchronizer::Objets::Revision#objet_attributes` devient private
`Synchronizer::Objets::Batch::Base#all_objets_attributes_with_eager_loaded_records` est inliné dans son seul usage dans le même fichier
=> 2. refacto synchro objets : nouveau logger + methode action

app/jobs/synchronizer/communes/batch/base.rb, app/jobs/synchronizer/communes/batch/eager_load_store.rb, app/jobs/synchronizer/communes/parser.rb, app/jobs/synchronizer/communes/revision.rb, app/jobs/synchronizer/communes/row.rb, app/jobs/synchronizer/communes/synchronize_all_job.rb, app/models/commune.rb, app/models/user.rb, db/migrate/20240216134435_allow_recensements_user_id_nil.rb, db/schema.rb, spec/jobs/synchronizer/communes/batch/base_spec.rb, spec/jobs/synchronizer/communes/revision_spec.rb, spec/jobs/synchronizer/communes/row_spec.rb, spec/jobs/synchronizer/communes/synchronize_all_job_spec.rb
cf https://www.notion.so/atelier-numerique/mettre-jour-les-emails-des-communes-1da9f6e6698c42b3906e83319e0cc8d3
Une bonne moitié des 600 l+ sont des tests. 
Il y a deux changements fonctionnels principaux
1. créer les communes "manquantes" (selon les codes insees des objets présents dans CO)
2. remplacer les emails ayant changés sur Service Public
Cette PR fait à la fois un gros refacto et ces changements fonctionnels, ce n’est pas bien, mea culpa.
Le refacto aligne grandement l’organisation du module `Synchronizer::Communes` sur celle du module `Synchronizer::Objets` : 
- `Parser` : transforme une ligne CSV en attributs de `Commune` et de `User`
- `Row#in_scope?` : détermine si une ligne CSV est à exclure en utilisant des validations AR
- `Revision#synchronize` : applique les modifs dans …
=> 3. import : création communes manquantes + MàJ des emails

db/migrate/20240219175302_add_index_objets_lieu_actuel_code_insee.rb, db/schema.rb
l’absence de cet index implique probablement des perfs bien dégradées
je n’avais pas pensé à l’ajouter en même temps que le nouveau champ 🤦
=> ajout d’un index sur objets.lieu_actuel_code_insee

app/jobs/synchronizer/objets/batch/base.rb, app/jobs/synchronizer/objets/revision_update_concern.rb
Changement simple et concis : 
| on importe maintenant les objets POP dans CO même s’il n’y a pas encore de commune correspondante au code INSEE actuel dans la DB de CO.
L’idée est donc qu’on va lancer dans l’ordre :
1. la synchro des objets
2. la synchro des communes
et c’est à l’étape 2 que les communes "manquantes" seront créées si on trouve les infos dans Service Public pour ce code INSEE
logs d’un lancement sur un dump récent de prod : 
```
counters: {:not_changed=>246005, :update_with_commune_change=>159, :create=>2878, :update_ignoring_commune_change=>282}
```
- les 2878 `create` correspondent à des objets qu’on n’importait pas jusqu’ici car on n’a pas (encore) créé la commune correspondante en DB ; 
- les 159 `update_with_commune_change` correspondent à des objets qui ont …
=> Importer les objets orphelins (sans commune dans la db)

app/jobs/synchronizer/communes/row.rb, app/jobs/synchronizer/communes/synchronize_all_job.rb, spec/jobs/synchronizer/communes/synchronize_all_job_spec.rb
:lock: based on #1177 :lock:
- utiliser `Synchronizer::Communes::Row#code_insee` plutôt que d’accéder à la valeur brute dans la csv_row `commune_code_insee`
- utiliser `out_of_scope?` plutôt que `invalid?`
=> petits refactors sur Synchronizer::Communes::SynchronizeAllJob

app/jobs/synchronizer/objets/revision/base.rb, app/jobs/synchronizer/objets/revision/destroy_concern.rb, app/jobs/synchronizer/objets/revision/update_concern.rb, app/models/recensement.rb, app/views/conservateurs/deleted_recensements/show.html.haml, spec/jobs/synchronizer/objets/revision/base_spec.rb, spec/models/recensement_spec.rb
cf https://www.notion.so/atelier-numerique/g-rer-le-transfert-d-un-objet-d-une-commune-A-une-commune-B-lors-de-l-import-alors-que-la-commune--fb300ea12c9643c0ae1d381a4118b677
Cas considéré :
- un objet a été importé une première fois pour une commune A
- la commune a l’a recensé
- il change de code INSEE dans Palissy (ou bien un code WEB différent apparait = la commune a fusionné, ou bien l’objet est déplacé)
Lors du réimport, pour l’instant on ne change pas l’objet de commune et on laisse le recensement.
**Cette PR change l’objet de commune et soft delete le recensement.**
une petite PR pour une fois :) 
On génère maintenant le snapshot de l’objet dès l’instanciation des `Revision` et on le passe en paramètre à `Recensement#destroy_or_soft_delete!`. 
Jusqu’ici on laissait cette méthode …
=> import: déplacement des objets recensés

db/migrate/20240225180433_add_user_commune_id_foreign_key.rb, db/schema.rb
je me suis rendu compte au détour d’une ligne de code qu’il n’y avait pas cette contrainte de clé étrangère sur la colonne `users.commune_id`, ça me parait étonnant, cette PR la rajoute simplement
testé sur un dump de prod, ça ne pose pas de soucis, les données existantes sont cohérentes
=> migration: ajout d’une foreign key sur users.commune_id

app/jobs/synchronizer/communes/parser.rb, app/jobs/synchronizer/objets/parser.rb, app/lib/co/departement_stats.rb, app/models/departement.rb, db/migrate/20240226161226_add_lieu_actuel_departement_code_to_objets.rb, db/schema.rb, spec/jobs/synchronizer/objets/parser_spec.rb, spec/models/departement_spec.rb
Le champ `palissy_DPT` est peu utilisé dans l’app mais l’est plus sur metabase. Or, depuis qu’on importe les déplacements d’objets ce champ n’est plus le bon : il contient le code du département à date de protection.
On introduit donc un champ `lieu_actuel_departement_code` qui le parse depuis le code INSEE. 
Il y a environ ~50 objets dont le code INSEE n’arrive pas à être parsé en département. 6 contiennent `ETRANGER` . d’autres ont l’air juste erronnés genre 6 chiffres 🤷
=> migration: ajout de objets.lieu_actuel_departement_code

app/jobs/synchronizer/communes/row.rb, app/jobs/synchronizer/communes/synchronize_all_job.rb, app/models/commune.rb, app/models/edifice.rb, config/locales/fr.yml, db/migrate/20240225205526_add_last_in_scope_at_to_communes.rb, db/migrate/20240225205526_add_synchronized_at_to_communes.rb, db/schema.rb, spec/models/commune_spec.rb, spec/models/recensement_spec.rb
On ne supprime pour l’instant jamais les comunes. Cette PR introduit la suppression des communes dépréciées. On considère une commune dépréciée pour CO dans deux cas :
1. la commune n’a plus d’objet (dans le périmètre de CO)
ou 
2. la commune n’apparait plus comme une mairie principale
L’intérêt de supprimer ces communes dépréciées dans notre db est surtout de supprimer les users associés et libérer les emails pour leur éventuelle réutilisation. 
Dans le `Synchronizer::Communes::SynchronizeAllJob` on rajoute un cycle (càd un parcours du CSV) :
- on parcourt le CSV
- on filtre les lignes qui sont dans notre périmètre
- si une commune existe pour ce code INSEE dans notre db on met à jour son `synchronized_at`
- une fois tout le CSV parcouru, on considère que toutes les communes dont le …
=> 3. import: suppression de communes (et users) dépréciés

app/jobs/synchronizer/api_client_opendatasoft_concern.rb, app/jobs/synchronizer/communes/revision.rb, app/jobs/synchronizer/communes/synchronize_all_job.rb, app/models/user.rb, spec/models/commune_spec.rb
je suis surpris j’étais sûr que ça fonctionnait correctement 🤔 
ce qu’il manquait c’est la validation de l’unicité de l’email au niveau ActiveRecord - ce n’était fait qu’au niveau de postgres avec l’index unique.
j’ai rajouté un test au niveau de commune qui vérifie l’invalidité d’une commune avec un user attribute avec un email déjà utilisé
cavaliers applicatifs de cette PR : 
- simplification de la méthode pour passer les CSVs déjà téléchargés en local
- petit refacto des logs de la synchro pour les rendre plus lisibles 
- correction de l’incrémentation de la progressbar qui débordait un peu
=> correction synchro communes lorsque l’email est déjà utilisé

app/controllers/communes/recensements_controller.rb, app/models/recensement.rb, app/models/user.rb, db/migrate/20240228143918_remove_user_id_from_recensements.rb, db/schema.rb, spec/factories/recensement.rb, spec/features/communes/read_rapport_spec.rb, spec/features/conservateurs/accept_dossier_spec.rb, spec/models/bordereau/pdf_spec.rb, spec/models/recensement_spec.rb
cette colonne est inutile. On pourrait d’ailleurs aussi supprimer dossiers.user_id
il faudra merger cette PR si des recensements soft deleted se retrouvent avec des user_id pour une raison inconnue
```rb
Recensement.only_deleted.where.not(user_id: nil)
```
j’ai fait un test du happy path complet en local recensement commune examen conservateur je n’ai pas vu d’erreurs
=> migration: remove useless recensements.user_id

Procfile, config/database.yml
The production worker is unable to run jobs:
ActiveRecord::ConnectionTimeoutError:
could not obtain a connection from the pool within 5.000 seconds
This makes sense because the pool size is currently 5, and both Good Job and Rails are being told to use 5 threads. Assuming the web server is busy or keeps DB connections alive, it means the worker is starving on the side.
Bump the pool size to the recommended calculation[1].
[1]: https://github.com/bensheldon/good_job/issues/669#issuecomment-1188022040
=> db: bump the connection pool size

app/models/session_authentication.rb, spec/models/session_authentication_spec.rb
Actuellement, lorsqu'une commune essaie de se connecter avec un code expiré, elle voit ce message d'erreur :
Elles contactent ensuite le support pour connaître la marche à suivre.
Dans un premier temps, nous clarifions le message pour qu'elles sachent qu'il est possible de redemander un code en cliquant sur le bouton adéquat.
=> Améliorer le message d'erreur lorsqu'une commune essaie de se connecter avec un code expiré

app/presenters/photo_presenter.rb
Actuellement le bouton Télécharger de la galerie renvoie vers une page d'erreur 404
Ce problème n'apparait à priori qu'en production.
Il manquait le préfixe `/rails` dans l'URL du reverse proxy, qui est ajouté uniquement avec l'option `only_path: true` dans le helper `rails_blob_path`
=> Correctif du bouton Télécharger une photo dans la galerie

config/application.rb
Suite à un constat de mauvais affichage de l'heure sur les emails de codes de session et des messages dans la messagerie, je me suis aperçu que la timezone n'était pas configurée.
Après un tour dans le code pour vérifier où on utilisait des `Time.zone.now` ou `Time.zone.today`, cela ne devrait pas avoir d'impact sur les jobs.
=> Utilisation de la timezone Paris

Gemfile
FactoryBot ne sert qu'en test ou développement, il est donc inutile de la charger en production. La charger alourdit l'empreinte mémoire, et si la librairie monkey-patch encore des classes Ruby ou Rails, cela peut avoir des conséquences inattendues.
=> Inutile de charger FactoryBot en production

config/initializers/devise.rb
Lors du démarrage de l'application, Devise cherche la clé `secrets_key_base` dans `Rails.application.secrets`, ce qui déclenche le message de déprécation suivant :
> WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2.
En attendant que Devise corriger le problème, il suffit d'indiquer où trouver cette clé explicitement.
[Issue sur Devise](https://github.com/heartcombo/devise/issues/5644)
=> Évite l'affichage d'un message de déprécation causé par Devise

app/jobs/export_memoire_csv_job.rb, app/models/memoire_export_photo.rb, spec/models/memoire_export_photo_spec.rb
Depuis l’admin “Export pour POP”, lorsqu’on génère un export des photos (à destination de la MPP), le CSV ne se génère jamais.
Après avoir creusé dans la tâche responsable de la génération de l’export `ExportMemoireCsvJob` plante avec l’erreur suivante :
`NameError: uninitialized constant Synchronizer::ApiClientJson`
En fait, pendant l’export on va ré importer certains champs de Palissy qui ne sont pas dans notre base. Mais cet import ne fonctionne pas car il se base sur l’ancienne méthode qui n’est plus disponible (on est censés passer uniquement par le portail Open Data du ministère de la Culture).
Les champs en question sont DATE, AUTR, ADRS et LIEU, respectivement utilisés pour remplir les champs Mémoire DATEOEU, AUTOEU, ADRESSE, LIEU.
La MPP est d'accord pour omettre ces champs lors …
=> Correctif de l'export Mémoire

app/models/objet.rb, app/views/shared/_objet_attributes.html.haml
Certains objets n'ont pas beaucoup d'informations, ce qui provoque un affichage incomplet. Je propose de générer un nom à partir des données présentes si nécessaire.
En remplaçant "N/A" par "Inconnu" on évite un problème d'accessibilité (abréviation non identifiée), tout en étant plus explicite.
=> Corrige l'affichage des objets incomplets

app/views/pages/stats.html.haml
À cause de l'indentation, le contenu n'était pas inclus dans le conteneur, et s'étalait en pleine largeur. Sur écran large, c'était particulièrement gênant.
=> Corrige l'affichage de la page statistiques

app/frontend/stylesheets/utilities.css, app/views/presse/index.html.haml, app/views/presse/show.html.haml
Une seule tuile par ligne sur petits écrans, pour éviter de n'avoir qu'un seul mot par ligne à cause de l'espacement horizontal du composant.
Sur les pages d'articles, le logo la date et le nom de l'auteur s'empilent sur mobile pour être plus lisibles.
=> Amélioration du responsive sur les pages presse

package-lock.json
Corrige le focus invisible sur le logo.
J'ai vérifié, il ne devrait pas y avoir d'impact sur l'affichage car il n'y a que des correctifs (comme indiqué par le numéro de version).
[Voir tous les changements](https://github.com/GouvernementFR/dsfr/compare/v1.11.0...v1.11.2)
=> Update @gouvfr/dsfr 1.11.0 -> 1.11.2

app/models/recensement.rb, app/models/recensement_wizard/base.rb, app/models/recensement_wizard/step1.rb, app/models/recensement_wizard/step2.rb, app/models/recensement_wizard/step3.rb, app/models/recensement_wizard/step4.rb, app/models/recensement_wizard/step5.rb, app/models/recensement_wizard/step6.rb, app/models/recensement_wizard/step7.rb, spec/models/recensement_spec.rb, spec/requests/recensement_wizard_spec.rb
Quand un objet est déplacé dans une autre commune, on ne demande pas s'il est recensable, et l'attribut `recensable` reste à `nil` ce qui empêche de valider le recensement ([erreur Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/100891/)).
Le commit f05e468c4eb398f34be0d2abc1cfe799046c08c8 enregistre automatiquement une valeur inférée de la localisation de l'objet si `recensable` est à nil au moment où le référencement est complété.
J'ai ajouté des tests pour être sûr que cette modification n'a pas d'effets de bords, corrigé une coquille et amélioré la lisibilité du code et des tests au passage.
=> Corrige l'enregistrement du recensement pour un objet déplacé

app/models/recensement.rb, app/models/recensement_wizard/step1.rb, app/models/recensement_wizard/step3.rb
Suite à la détection d'un bug lorsqu’une commune finalise le recensement d’un objet déclaré comme déplacé dans une autre commune, il nous a semblé judicieux d'intégrer la méthode `RecensementWizard::Base#reset_recensement_data_for_next_steps`dans la classe `Recensement`.
=> Refactoring sur le reset de data de recensement

Gemfile, Gemfile.lock, config/environments/test.rb, spec/active_storage_safe_purge_spec.rb, spec/features/public_pages_spec.rb, spec/rails_helper.rb
Je sais qu'il y a de la feature à sortir, mais j'ai identifié quelques améliorations qui permettent de gagner du temps quand on fait tourner les tests. J'avais notamment remarqué que certains tests lançaient des requêtes HTTP, qui finissaient en timeout quand mon ordi n'avait pas de connexion Internet. Ce sont des choses faciles à bloquer avec un gain de performances non négligeable je pense.
=> Améliore les tests

README.md, SECURITY.md, app/mailers/admin_mailer.rb, app/mailers/application_mailer.rb, app/mailers/campaign_v1_mailer.rb, app/mailers/user_mailer.rb, app/views/conservateurs/bordereaux/new.html.haml, app/views/pages/accueil_conservateurs.html.haml, app/views/pages/aide.html.haml, app/views/pages/conditions.html.haml, app/views/pages/confidentialite.html.haml, app/views/pages/declaration_accessibilite.html.haml, app/views/pages/home.html.haml, app/views/shared/_footer.html.haml, app/views/shared/campaigns/_form.html.haml, config/initializers/contact_email.rb, config/initializers/devise.rb, contenus/content_blobs/documentation_conservateur.md, scripts/send_test_mail.rb, spec/lib/co/send_in_blue_client_spec.rb, spec/mailers/campaign_v1_mailer_spec.rb, spec/mailers/conservateur_mailer_spec.rb, spec/mailers/user_mailer_spec.rb
Beta Gouv nous demande de ne plus envoyer nos emails avec une adresse "De:" en collectifobjets@beta.gouv.fr.
À la place, on utilise contact@collectifobjets.beta.gouv.fr.
=> Migration de l'adresse émettrice des emails transactionnels

app/controllers/admin/session_codes_controller.rb, app/controllers/users/session_codes_controller.rb, app/controllers/users/sessions_controller.rb, app/jobs/sanity/remove_old_session_codes_job.rb, app/models/session_authentication.rb, app/models/session_code.rb, app/models/user.rb, app/views/admin/session_codes/index.html.haml, app/views/pages/admin.html.haml, app/views/user_mailer/session_code_email.mjml, app/views/user_mailer/session_code_email.text.erb, app/views/users/session_codes/new.html.haml, app/views/users/sessions/_faq.html.haml, app/views/users/sessions/new.html.haml, config/locales/fr.yml, config/routes.rb, spec/models/session_authentication_spec.rb, spec/models/session_code_spec.rb
=> Facilite la connexion utilisateur

scripts/s3buckets/cors-staging.json
La configuration CORS ne prenait pas en compte l'URL de staging fournie par Scalingo, c'est désormais le cas.
À noter que l'URL https://staging.collectifobjets.org devra être retirée le jour où ce domaine n'est plus utilisé.
=> Configuration CORS en staging

app/jobs/synchronizer/photos/synchronize_all_job.rb, app/presenters/photo_presenter.rb, config/initializers/content_security_policy.rb, config/initializers/memoire_db.rb, db/migrate/20240624161724_replace_palissy_photos_url.rb, db/schema.rb
Les photos importées de la base Mémoire vont migrer d'AWS vers OVH.
Actuellement nous stockons l'URL complète de la photo dans le champ JSON `palissy_photos` de la table `objets`, comme par exemple : https://s3.eu-west-3.amazonaws.com/pop-phototeque/memoire/OA052_065200001/OA052_065200001.jpg
Suite à la migration, seule la racine `s3.eu-west-3.amazonaws.com` va changer.
Plusieurs options possibles pour s'adapter côté Collectif Objets : 
- Remplacer la racine à la volée au moment de l'affichage de la photo
- Avantage : simple à faire, pas de migration de la base
- Inconvénient : laisse des URLs avec la racine AWS en base
- Migrer la base avec les nouvelles URLs
- Avantage : base de données cohérente
- Inconvénient : migration lente (on remplace des données dans un champ JSON)
- Migrer la …
=> Migration des photos Mémoire vers OVH

app/controllers/communes/recensements_controller.rb, app/models/commune.rb, app/models/dossier.rb, app/models/objet.rb, app/models/recensement.rb, app/policies/communes/recensement_policy.rb, db/migrate/20240710131820_link_draft_recensements_with_dossier.rb, db/schema.rb, spec/factories/commune.rb, spec/factories/dossier.rb, spec/models/campaign_recipient_spec.rb, spec/models/objet_spec.rb, spec/models/recensement_spec.rb, spec/policies/communes/recensement_policy_spec.rb, spec/requests/recensement_wizard_spec.rb
Dans le re-recensement, une commune peut désormais avoir plusieurs dossiers.
À la création du tout premier recensement de la commune, s'il reste en brouillon il n'est pas associé au dossier de la commune (qui n'a pas encore été créé). Il devient donc impossible de retrouver le recensement, et d'en créer un nouveau pour cet objet (Erreur "Objet n'est pas disponible" liée à la contrainte d'unicité).
=> Corrige les recensements orphelins

app/controllers/communes/completions_controller.rb, app/controllers/conservateurs/communes_controller.rb, app/jobs/synchronizer/objets/revision/destroy_concern.rb, app/jobs/synchronizer/objets/revision/update_concern.rb, app/lib/co/communes/objets_list.rb, app/models/edifice.rb, app/models/objet.rb, app/views/conservateurs/communes/show.html.haml, spec/jobs/synchronizer/objets/revision/base_spec.rb, spec/models/objet_spec.rb
Actuellement on récupère le recensement en cours d'un objet via une méthode `def recensement [...] end`.
On va privilégier une association `has_one :recensement`, de manière à être plus proche des standards Rails et pouvoir bénéficier du `includes(:recensement)` pour éviter certaines requêtes N+1. 
NB : l'includes ne fonctionne pas pour la page `conservateur/communes/:id/`, ce qui est fort dommage. Peut-être parce qu'on passe l'objet à un `ObjetCardComponent`.
=> Utilisation d'une association entre Objet et Recensement

app/frontend/stylesheets/components/testimonials.css, app/frontend/stylesheets/components/unfold.css, app/frontend/stylesheets/utilities.css
Le sélecteur `[data-fr-scheme]` correspond au choix utilisateur (clair/sombre/système), les styles qui se basent dessus ne s'appliquent donc que quand l'utilisateur choisit le mode sombre.
Il faut utiliser `[data-fr-theme]` pour que les styles s'appliquent quand le mode sombre est actif, que ce soit par choix de l'utilisateur ou activé par le système.
=> Fix les sélecteurs pour le dark theme

app/controllers/pages_controller.rb
Le compteur d'objets sur la page d'accueil n'était plus bon car il ne prenait pas en compte la possibilité du re-recensement.
NB : il n'est pas tout à fait le même que sur Metabase car il est mis à jour tous les 24h environ
=> Corrige le compteur d'objets déjà recencés suite au re-recensement

.github/workflows/ci.yml
L'installation de `libvips` ne passe plus en CI, ce qui fait échouer tous les tests.
Il semble que la version d'Ubuntu utilisée par Github Actions est passée en EOL, le package `libvips` a changé d'adresse.
```
Err:25 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libpoppler118 amd64 22.02.0-2ubuntu0.4
404  Not Found [IP: 52.147.219.192 80]
Err:26 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libpoppler-glib8 amd64 22.02.0-2ubuntu0.4
404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/poppler/libpoppler118_22.02.0-2ubuntu0.4_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/poppler/libpoppler-glib8_22.02.0-2ubuntu0.4_amd64.deb  404  Not Found [IP: …
```
=> Corrige l'installation de libvips qui échoue désormais en CI

app/controllers/communes/completions_controller.rb, app/jobs/remove_personal_information_job.rb, app/jobs/schedule_remove_personal_information_job.rb, app/models/dossier.rb, app/models/dossier_completion.rb, app/views/communes/completions/new.html.haml, app/views/communes/completions/show.html.haml, app/views/conservateurs/communes/show.html.haml, app/views/pages/conditions.html.haml, app/views/pages/confidentialite.html.haml, app/views/pages/mentions_legales.html.haml, config/locales/fr.yml, db/migrate/20240715122757_add_recenseur_to_dossiers.rb, spec/jobs/remove_personal_information_job_spec.rb, spec/jobs/schedule_remove_personal_information_job_spec.rb, spec/requests/completion_spec.rb
=> Demande le nom du recenseur et met à jour les mentions légales

app/controllers/admin/conservateurs_controller.rb
Actuellement les admins sont redirigés vers la page conservateur/départements quand ils incarnent un conservateur, même si celui-ci n'a accès qu'à un seul département. Ce commit le corrige.
=> Redirige sur le seul département quand on incarne un conservateur n'en ayant qu'un

app/helpers/recensement_helper.rb, app/views/communes/recensements/_step7.html.haml, spec/features/communes/recensement_spec.rb
Apparemment, plusieurs communes ne comprennent pas l'usage du crayon. Ajouter le texte "Modifier" pour clarifier la fonction.
=> Clarifie la fonction du crayon dans le récap recensement commune

app/controllers/conservateurs/departements_controller.rb
La dernière commune du tableau était répétée de page en page, sauf si on triait par nom.
Corrigé, mais en bidouillant parce que l'API de tri de Ransack est… [contre-intuitive](https://github.com/activerecord-hackery/ransack/issues/994).
=> Corrige les communes répétées dans la vue tableau du département

app/controllers/conservateurs/departements_controller.rb, app/helpers/campaign_helper.rb, app/jobs/campaigns/refresh_campaign_stats_job.rb, app/lib/co/departement_stats.rb, app/models/campaign.rb, app/models/campaign_stats.rb, app/models/commune.rb, app/models/dossier.rb, app/models/objet.rb, app/models/recensement.rb, app/views/admin/campaigns/show.html.haml, app/views/conservateurs/departements/_stats.html.haml, app/views/conservateurs/departements/show.html.haml, app/views/conservateurs/departements/show_map.html.haml, app/views/shared/campaigns/_stats.html.haml, config/initializers/good_job.rb, db/migrate/20240801080839_add_campaign_id_to_dossiers.rb, db/schema.rb
=> Corrige les statistiques de campagnes apres re-recensement

app/models/exports/mpp.rb
Le tri était effectué par date de création des recensements, mais l'affichage indiquait la date d'acceptation des dossiers. On trie désormais selon cette dernière pour que l'affichage soit cohérent.
=> Modifie le tri des exports MPP pour être plus cohérent

app/controllers/pages_controller.rb, app/views/pages/guide.haml, app/views/pages/pdf_embed.html.haml, config/routes.rb
Les fiches ont été extraites de ce contrôleur dans le commit 1272a73c9186be7ff2085075e4ce279a211384ff.
Corrige l'erreur Sentry #52860 (825 occurrences).
=> Simplification de l'affichage du guide de recensement

app/controllers/admin/dossiers_controller.rb, app/models/dossier.rb, app/views/admin/communes/show.html.haml, config/routes.rb
La fonctionnalité n'est plus utilisée et semble de plus être au mauvais endroit, on peut donc l'enlever.
=> Suppression de la fonction "Repasser la commune en recensement et le dossier en construction"

app/models/user.rb
Aujourd'hui, lorsqu'on supprime une commune qui n'a pas d'objets lors de l'import, une erreur apparaît si des codes de connexion existent encore en base.
Cette PR corrige le problème en supprimant en même temps que la commune.
=> Suppression des codes de session lors de la suppression d'une commune

app/controllers/admin/attachments_controller.rb
La rotation et le marquage en "non exportable" d'une photo dans un export Mémoire ne fonctionnaient plus.
Il s'agissait d'un mauvais path de partial suite à la ré organisation des fichiers lors de l'ajout de l'export des objets manquants et déplacés.
=> Correctif de la manipulation de photos dans les exports Mémoire

app/controllers/admin/session_codes_controller.rb, app/models/session_authentication.rb, app/models/session_code.rb, app/views/admin/session_codes/_session_codes.haml, app/views/admin/session_codes/index.html.haml, spec/models/session_authentication_spec.rb
Les codes de connexion des communes sont valables 24h… Mais expirent dès qu'on se connecte, ce qui n'est pas évident pour les communes. Une fois que les utilisateurs se sont déconnectés, ils doivent redemander un code.
Cette PR permet d'utiliser un code pour se connecter autant de fois qu'on veut tant qu'il est valide.
C'est ce qui explique qu'une même commune puisse avoir plusieurs codes générés dans la même journée, alors qu'ils sont sensés être valides durant 24h.
Au passage, j'ai corrigé l'affichage de la pagination des codes de connexion côté admin (le premier écran affichait 0, alors qu'on s'attend plutôt à commencer à 1).
=> Permettre aux communes de se connecter avec un code deja utilisé

app/controllers/admin/communes_controller.rb, app/controllers/admin/session_codes_controller.rb, app/views/admin/communes/show.html.haml, app/views/admin/session_codes/index.html.haml, config/routes.rb
Puisque les emails mettent parfois longtemps à arriver, ou finissent en spam voire silencieusement avalés par les filtres anti-spam, on simplifie un peu plus la gestion des codes de connexion pour les admins.
- Le code de connexion courant est désormais affiché sur la page admin de la commune.
- S'il n'y a pas de code, le bouton permet d'en générer un, et l'affiche dans la page.
- Si on clique sur le bouton qui contient le code, on arrive sur la page de connexion de la commune, avec le code préremplit. Il n'y a plus qu'à copier-coller dans un mail pour la commune, ou à leur dicter au téléphone.
- Un mini moteur de recherche permet de chercher une commune depuis la liste des codes de connexion.
=> Simplifier la gestion des codes de connexion par les admins

app/controllers/conservateurs/bordereaux_controller.rb, app/helpers/conservateur_helper.rb, app/jobs/generate_bordereau_pdf_job.rb, app/models/bordereau/pdf.rb, app/models/bordereau/recensement_row.rb, app/views/conservateurs/bordereaux/_edifice.html.haml, app/views/conservateurs/bordereaux/create.turbo_stream.erb, app/views/conservateurs/bordereaux/index.html.haml, app/views/conservateurs/bordereaux/new.html.haml, app/views/conservateurs/departements/index.html.haml, config/locales/fr.yml, config/routes.rb, spec/features/conservateurs_pages_spec.rb, spec/models/bordereau/pdf_spec.rb
À la demande des CAOA, les bordereaux de récolement ont été modifiés : 
Au passage, quelques améliorations de l'interface et du code :
=> Mise à jour des bordereaux de récolement

Gemfile.lock, app/controllers/admin/comments_controller.rb, app/controllers/admin/conservateurs_controller.rb, app/controllers/communes/campaign_recipients_controller.rb, app/controllers/communes/completions_controller.rb, app/controllers/communes/recensements_controller.rb, app/controllers/communes/users_controller.rb, app/controllers/concerns/campaign_recipients_controller_concern.rb, app/controllers/concerns/campaigns_controller_concern.rb, app/controllers/concerns/messages_controller_concern.rb, app/controllers/conservateurs/accepts_controller.rb, app/controllers/conservateurs/analyses_controller.rb, app/controllers/conservateurs/conservateurs_controller.rb, app/controllers/survey_votes_controller.rb, app/controllers/users/sessions_controller.rb, spec/requests/recensement_wizard_spec.rb
Les nouvelles versions de Rails utilisent une version plus récente de Rack.
Celle-ci a récemment renommé le code 422 `:unprocessable_content` (précédemment appelé `:unprocessable_entity`), suivant en cela la décision de la RFC HTTP officielle.
Cette PR corrige les tests dans #1365, #1366, et #1367.
=> Mise à jour de Rack

README.md, app/components/conservateurs/objet_card_component.rb, app/helpers/commune_helper.rb, app/models/commune.rb, app/models/concerns/communes/include_statut_global_concern.rb, app/views/conservateurs/communes/show.html.haml, spec/models/commune_spec.rb
Clarifie la différence entre les dossiers à examiner en priorité et ceux qu'il est bon de consulter mais ne nécessitent pas d'action urgente.
En effet, le texte "Examen optionnel" porte à croire qu'il n'est pas nécessaire d'ouvrir le dossier, pouvant conduire les conservateurs à ignorer des questions ou informations pertinentes envoyées par les communes lors de leur recensement.
Fait suite à la PR #1361.
=> Modifie le texte et les couleurs des statuts des communes

app/controllers/admin/admin_users_controller.rb, app/views/admin/admin_users/_form.html.haml, app/views/admin/admin_users/edit.html.haml, app/views/admin/admin_users/index.html.haml, app/views/admin/admin_users/new.html.haml, app/views/admin/admin_users/show.html.haml, app/views/pages/admin.html.haml, config/routes.rb, spec/features/admin_pages_spec.rb, spec/requests/admin_users_spec.rb
Puisque l'équipe se réduit, et que des accès n'ont pas été supprimés suite à des départs, ces nouveaux écrans permettent de voir les administrateurs et leur ancienneté, et de révoquer leur accès si besoin.
=> Ajoute un écran d'administration des administrateurs

config/initializers/content_security_policy.rb
Comme indiqué dans le commentaire, autoriser Loom dans la CSP n'était nécessaire que tant que des vidéos étaient hébergées dessus. Ce n'est plus le cas, il faut donc mettre la CSP à jour.
=> Supprime Loom de la CSP puisque les videos ont été migrées

app/controllers/conservateurs/campaigns_controller.rb, app/views/shared/campaigns/_show_content.html.haml
Le code a été réorganisé pour améliorer la lisibilité, et s'interrompre plus rapidement si l'utilisateur tente de créer une campagne pour un département auquel il n'a pas accès.
=> Simplifie l'utilisation des campagnes

app/mailers/campaign_v1_mailer.rb, app/views/shared/campaigns/_form.html.haml, spec/mailers/campaign_v1_mailer_spec.rb
Quand un mail est transféré, l'en-tête `Reply-To` n'est pas conservé. Dans ce cas, relativement fréquent, les mails des communes arrivent sur la boîte mail générique de la plateforme au lieu de la messagerie des conservateurs associés.
Avec ce changement, ce problème ne devrait plus se produire.
=> Envoie les campagnes avec l'adresse de messagerie

app/components/unfold_component/unfold_component.haml, app/controllers/conservateurs/campaigns_controller.rb, app/views/shared/campaigns/_edit_recipients_content.html.haml, app/views/shared/campaigns/_show_content.html.haml, config/locales/fr.yml
Le texte d'alerte sur les communes non examinées ajoutées à une nouvelle campagne n'était pas très clair. Il est donc reformulé pour être plus compréhensible, et les communes en cours d'examen ou de recensement sont désormais exclues de la sélection automatique, pour éviter que ce problème ne se produise à l'insu des conservateurs. 
Il leur est toujours possible de rajouter les communes en cours d'examen en cliquant sur "Tout sélectionner" ou en cochant ces communes une par une, auquel cas le texte d'alerte sera affiché.
Le bandeau indiquant que les communes en cours d'examen sont désormais sélectionnées par défaut est retiré puisque ce n'est plus le cas.
J'en ai profité pour agrandir la zone de clic du bouton "Afficher tout…" dans le composant Unfold, pour améliorer l'ergonomie.
=> Corrige le texte d'alerte sur les communes à rerecenser

app/models/commune.rb, spec/jobs/campaigns/cron_job_spec.rb, spec/models/commune_spec.rb
Suite au renommage des statuts "Examen optionnel" et "À examiner" en "À examiner" et "À examiner en priorité", les communes non prioritaires sont affichées comme tel 10 jours durant.
Ce changement raccourcit le délai d'envoi du mail "Objets verts" pour qu'il parte le lendemain (ou le lundi suivant si le dossier est soumis le vendredi). De cette manière, les dossiers non prioritaires basculeront plus rapidement au statut "À examiner" afin d'aider les conservateurs à prioriser leurs analyses.
=> Envoie le mail objets verts dès le lendemain

app/helpers/objet_helper.rb, app/models/edifice.rb, app/views/admin/communes/show.html.haml, app/views/conservateurs/bordereaux/_edifice.html.haml, app/views/edifices/_edifice.html.haml, app/views/edifices/_list.html.haml, app/views/edifices/_title.html.haml
Certains édifices n'ont pas de nom, ce qui provoque une erreur si on essaie de le capitaliser.
=> Corrige l'erreur "édifice non renseigné" sur l'écran des bordereaux

app/mailers/conservateur_mailer.rb, app/mailers/user_mailer.rb, lib/mailer_previews/conservateur_mailer_preview.rb, spec/mailers/conservateur_mailer_spec.rb, spec/mailers/user_mailer_spec.rb
=> Modifie l'adresse d'envoi des mails aux communes

README.md, app/mailer_views/campaign_v1_mailer/_objet_photo.mjml, app/mailer_views/shared/_footer.mjml, app/mailer_views/shared/_header.mjml, app/views/conservateurs/departements/index.html.haml, app/views/conservateurs/passwords/new.haml, app/views/conservateurs/sessions/new.html.haml, app/views/devise/mailer/define_password_instructions.mjml, app/views/devise/mailer/reset_password_instructions.mjml, config/environments/production.rb, config/initializers/contact_email.rb, config/initializers/devise.rb, public/404.html, public/500.html
=> feat: Récupère la configuration email depuis l'environnement
